# Generated by Django 5.0.1 on 2024-02-09 08:29

import DataAccess.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='orgnizer_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user_profile_image', models.ImageField(blank=True, upload_to='profile')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='role_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='organizer_info_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('organization_name', models.CharField(max_length=150)),
                ('languages', models.CharField(blank=True, max_length=20, null=True)),
                ('identification', models.FileField(upload_to='IdentificationFiles')),
                ('maxchanges', models.CharField(blank=True, max_length=20, null=True)),
                ('minchanges', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.category_master')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.orgnizer_master')),
            ],
        ),
        migrations.AddField(
            model_name='orgnizer_master',
            name='role',
            field=models.ForeignKey(default=DataAccess.models.get_rol_org, on_delete=django.db.models.deletion.CASCADE, to='DataAccess.role_master'),
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('role', models.ForeignKey(default=DataAccess.models.get_rol_cust, on_delete=django.db.models.deletion.CASCADE, to='DataAccess.role_master')),
            ],
        ),
        migrations.CreateModel(
            name='whoview_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.customer')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.orgnizer_master')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.orgnizer_master')),
            ],
        ),
    ]
