# Generated by Django 5.0.1 on 2024-02-09 08:31

import DataAccess.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization_portfolio_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_img', models.FileField(upload_to='OrganizationPortfolio')),
                ('org', models.ForeignKey(default=DataAccess.models.get_org_id, on_delete=django.db.models.deletion.CASCADE, to='DataAccess.orgnizer_master')),
            ],
        ),
    ]
